[package]
name = "aoc2015"
version = "0.1.0"
authors = ["David Kennedy <david.kennedy@workday.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
regex = "1"
